### ISSUE TITLE
[CI] Addition of tests for Meshery UI (Umbrella issue)

### ISSUE THREAD

**Issue by kushthedude** [meshery/meshery#1037]
**Description**

We have already integrated the Cypress testing framework. Let's start adding more & more tests for our UI.

#### Integration Tests(Routes):

- [x] ~`provider` (#1778)~
- [ ] `/management`
- [ ] `/performance`
- [x] ~`/userpreference` (#1853)~ 
- [ ] `/smi_results`
- [ ] `/results`
- [ ] `/settings` (Environment (#2316), Service Meshes (#2317), Metrics, Performance)
- [ ] `/index` (#2315)
- [ ] `/configuration` (#4582)

#### E2E Tests(Routes):
- [ ] `/management`
- [ ] `/performance`
- [x] ~`/userpreference` (#1862)~
- [ ] `/smi_results`
- [ ] `/results`
- [ ] `/settings` (~Environment (#2139)~, ~Service Meshes (#2218)~, Metrics, Performance)
- [ ] `/index`
- [ ] - [ ] `/configuration` (#4582)
- [ ] Add integration tests for /configuration/applications route
- [ ] Add integration tests for /configuration/filters route
- [ ] Add integration tests for /configuration/patterns route
**E2E Tests (these are more usecase or scenario wise as they'll touch multiple routes and multiple pages in each child issue with actual server responses):**
- [ ] Add E2E tests to Deploy Applications/Filters/Patterns Configuration through Meshery UI (#4826)
- [ ] Add E2E tests to Edit Applications/Filters/Patterns Configuration through Meshery UI
- [ ] Add E2E tests to Delete Applications/Filters/Patterns Configuration through Meshery UI"

**Additional Context**

**Comment by tsingh2k15** [comment]
@kushthedude I can contribute. I will take a look and share the component which I can cover.

**Comment by kushthedude** [comment]
> @kushthedude I can contribute. I will take a look and share the component which I can cover.

Great! AFAIK provider-ui can work without server, performance page, settings page & results page can render if the server is not working.

**Comment by ramrodo** [comment]
@kushthedude I want to contribute to creating tests for the `provider-ui`. Should I create an issue for this specific route or how can we coordinate this?

**Comment by kushthedude** [comment]
> @kushthedude I want to contribute to creating tests for the `provider-ui`. Should I create an issue for this specific route or how can we coordinate this?

Hi @ramrodo , Provider-UI only has single route so I guess we don't need to create a different issue and you can just refer your PR with this issue 😄

**Comment by leecalcote** [comment]
@kushthedude I added the label for parent issue given that the title and description call for any number of child issues to be created. It’d be nice to breakout this work into sub-issues.

**Comment by kushthedude** [comment]
Let me break the issue down and mention each and every route/tests in the issue description so that we can track the progress as a whole/

**Comment by leecalcote** [comment]
@ramrodo it would be great to get a short overview and demo from you on Cypress on Friday's community call. Most community members are unfamiliar with this. Are you available to attend this Friday's community meeting? 10am to 11am Central?

**Comment by ramrodo** [comment]
> @ramrodo it would be great to get a short overview and demo from you on Cypress on Friday's community call. Most community members are unfamiliar with this. Are you available to attend this Friday's community meeting? 10am to 11am Central?

Sounds good! 11am central works better for me.

**Comment by leecalcote** [comment]
Ok, understood. Here is the community calendar with the various meetings we have each day - https://bit.ly/2SbrRhe. Any of the Wednesday, Thursday, or Friday meetings would work.

**Comment by leecalcote** [comment]
Also, https://layer5.io/community#meet

**Comment by ramrodo** [comment]
Oh I see. So, Wednesday November 4th is ok for me (the Friday one overlaps with other job meeting)

**Comment by kushthedude** [comment]
The issue had been split into 14 milestones, please comment on which one would you like to accomplish so that we may assign you the one.

**Comment by ramrodo** [comment]
@kushthedude I want to start with `/userpreference` in the meantime I get familiarized more with the product.

**Comment by kushthedude** [comment]
Great !

**Comment by ramrodo** [comment]
@kushthedude I want to start with the **E2E test** for `/userpreference` also. Could you assign to me that one?

**Comment by leecalcote** [comment]
Great progress on this, @ramrodo. Are you still good with this single, epic issue or will the addition of smaller, child issues help?

**Comment by ramrodo** [comment]
> Great progress on this, @ramrodo. Are you still good with this single, epic issue or will the addition of smaller, child issues help?

I think we can split and detail the results and performance tests in order to cover all the cases. The others don't seem so complicated.

**Comment by ramrodo** [comment]
@kushthedude could you assign to me `e2e tests /settings`, please? I want to start working on that.

**Comment by ramrodo** [comment]
I'll be creating small issues addressing each path of this umbrella issue.
Please assign the issue yourself you're going to work on.

**Comment by leecalcote** [comment]
@sudo-NithishKarthik fyi

**Comment by warunicorn19** [comment]
@leecalcote @sudo-NithishKarthik I've started to read up on cypress, I'll try to write a test soon.

**Comment by sudo-NithishKarthik** [comment]
That's awesome @warunicorn19  🎉 
Actually, there's going to be some major architectural changes in Meshery UI and it would make more sense for us to delay the process of writing tests for sometime so that we don't find ourselves repeating the work.

**Comment by warunicorn19** [comment]
@sudo-NithishKarthik alrighty😃, just letting you know that whenever we do write tests, Im interested in doing so.😄

**Comment by sudo-NithishKarthik** [comment]
That being said, nothing's stopping you from exploring cypress, we still are going to cypress for E2E and integration testing, so, being competent in that would be really helpful.

**Comment by sudo-NithishKarthik** [comment]
@sayantan1413 , @warunicorn19 

This [blog](https://layer5ng.netlify.app/blog/meshery/functional-testing-with-cypress-in-meshery-ui) might be helpful i believe.

Also, can one of you guys make an effort to reference this blog in our `meshery-ui` contribution docs ?

**Comment by warunicorn19** [comment]
@sudo-NithishKarthik sure, I'll make it a part of the suggested reading, yes?

**Comment by sudo-NithishKarthik** [comment]
> @sudo-NithishKarthik sure, I'll make it a part of the suggested reading, yes?

Sounds good

**Comment by sandramsc** [comment]
This issue has been open for some time with no recent activity, unassigning to open it up for new contributors to give it a go.
