### ISSUE TITLE
[E2E]: Chore:Update playwright locators within indexui.spec.js file

### ISSUE THREAD

**Issue by AmTryingMyBest** [meshery/meshery#12364]
### Current Behavior
Meshery uses Playwright for e2e test automation. Playwright has a default format for adding unique locators to elements on the UI. The format or default naming convention is to label the elements as `data-testid="element-name"`
The `indexui.spec.js` file has some elements that are labeled as `data-test="element-name"` 
While this doesn't affect test behavior, it would be nice to have some kind of convention observed across the codebase where possible.

### Tasks:
- [ ] Find these attributes, and rename them so they match the default labelling
- [ ] Update tests where these locators are used so that they don't break

### Acceptance Tests
- [ ] Affected e2e tests pass as they did.
---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Contributing to Meshery's End-to-End Tests](https://docs.meshery.io/project/contributing/contributing-ui-tests)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)
