### ISSUE TITLE
[Performance] M3: Incorporate wkr2 as a Load Generator

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#212]
**Description**
See #126 for full description of Load Generator Integration Epic.

**Milestone 3: Incorporate wrk2 as a Load Generator**

- [ ] Create an implementation of the “LoadGeneratorInterface” for wrk2, “WRKLoadGenerator”
  - [ ] Which will invoke the wrk2 with the right parameters
  - [x] Extract and parse the json results and populate the “*periodic.RunnerResults” struct
  - [ ] Handle failure cases as well
  - [x] Given that wrk2 does not return the data points for the test
    - [x] We need to either extend wrk2 to be able to do that (OR)
    - [x] Make changes to the UI to behave differently for wrk2 tests
- [x] Update the load-test handler to include the load generator name as part of the request for initiating load test

**Additional context**
See [Load Generator Integration design doc](https://docs.google.com/document/d/1jZMOih3Qn1ixrq1Ve6fkdZZ4TuKNoF_qfClDZTnLNcw/edit#).

**Comment by kushthedude** [comment]
@NupurThakur27 wasn't this fixed in https://github.com/meshery/meshery/pull/486 ?

**Comment by NupurThakur27** [comment]
@kushthedude If you see the description of the Issue, the points which are still unchecked are not completed.  This issue was reopened because an interface needs to be implemented for wkr2 as a load generator.

**Comment by leecalcote** [comment]
I’m glad that this issue has been resurfaced. This is an issue that I was going to highlight a prework for the distributed performance testing project. With a third load generator coming into place, we need to create a clean interface to plugin load generators. This interface is part of Meshery’s extensibility story.

**Comment by kushthedude** [comment]
I agree before incorporating nighthawk, we should make our current load generators neat and clean.

**Comment by PluckyPrecious** [comment]
Knock Knock! @kushthedude  checking in for situation report.😃

**Comment by leecalcote** [comment]
Delivered.
