### ISSUE TITLE
[Chore] Update Handlers to use new Meshkit Errors

### ISSUE THREAD

**Issue by dhruv0000** [meshery/meshery#3275]
#### Current Behavior
Meshery Server (and its other components, like Adapters) use a centralized library, MeshKit, to provide uniform utilities (e.g. raising and logging errors). Currently, Meshery Server uses a now antiquated style of error logging with logrus.

#### Desired Behavior
Ideally, all use of logrus is replaced with use of MeshKit-style error logging.

#### Implementation
Meshery Handlers needs to be:
 - Updated to use meshkit errors. 
 - Switch to handler Log instead of `logrus`

Handlers to update:

  - [x] event streamer
  - [x] fetch results handler
  - [x] k8sconfig handlers
  - [x] load test handler
  - [x] load test mesh handler
  - [x] load test preferences handler (#3390)
  - [x] mesh ops handler
  - [x] meshery application handler
  - [ ] meshery filter handler
  - [ ] meshery pattern handler
  - [x] oam handler (#3387)
  - [x] performance profiles handler
  - [x] provider handler 
  - [x] schedule handler
  - [x] server spec handler
  - [x] session sync handler
  - [x] user handler
  - [x] Grafana handler
  - [x] Prometheus Handler
     
For reference, you can checkout  the `grafana handler` and `prometheus handler` or the [docs](https://docs.meshery.io/project/contributing-error).

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by leecalcote** [comment]
This is a fine-looking list, @dhruv0000. This issue makes for a good Epic (`issue/epic` label), which means that those like @josephmidura looking to knockout some of these are encouraged to create Child issues (`issue/child` label) to break down this work into bite-sized chunks.

**Comment by sayantan1413** [comment]
Hey @leecalcote Can I give it a try.

**Comment by debjani1413** [comment]
Hey @sayantan1413 I would like to pair up and work on the issue with you, what say???

**Comment by josephmidura** [comment]
@leecalcote I don't have the permissions to open in issue in Meshery.

**Comment by dhruv0000** [comment]
@josephmidura, @debjani1413 and @sayantan1413  I have created a child issues and assigned you some handlers to look into. 
Feel free to ping me in slack or here in Github if you feel stuck or confused.

**Comment by leecalcote** [comment]
> @leecalcote I don't have the permissions to open in issue in Meshery.

@josephmidura, that’s odd. Does this open up for you? - https://github.com/meshery/meshery/issues/new/choose  GitHub users who are not a member of the org have permission to create new issues. Your account should be entitled to not only create issues, but triage (update) issues that someone else has created, too.

**Comment by josephmidura** [comment]
> Does this open up for you? - https://github.com/meshery/meshery/issues/new/choose

Yes, that link opens, and I can open a bug report in Meshery and a bug report or feature request in Mesheryctl so I obviously misread something previously. Thanks for the follow up.

**Comment by suhaniii** [comment]
@sayantan1413 @debjani1413 @josephmidura @dhruv0000 @leecalcote  I am new, and would like to pair with you on this issue.

**Comment by dhruv0000** [comment]
Anyone wanna assign few of their handlers to with @suhaniii? @vijcheru @Chadha93 @samirparhi-dev

**Comment by suhaniii** [comment]
> Anyone wanna assign few of their handlers to with @suhaniii? @vijcheru @Chadha93 @samirparhi-dev

Sure

**Comment by Shreyas220** [comment]
hey, I am new as well, would like to be paired up with someone

**Comment by chetak123** [comment]
Hello everyone I am new to golang and if anyone has some pending tasks left, I am ready to help.

**Comment by leecalcote** [comment]
@sayantan1413 ^^

**Comment by josephmidura** [comment]
@sayantan1413 I'd also like to know if the errors were all updated.

**Comment by sayantan1413** [comment]
Yeah @josephmidura the issue on which you were working on #3279 is updated by @kumarabd.

**Comment by warunicorn19** [comment]
Issue has been solved.
