### ISSUE TITLE
[Patterns] Capabilities Versioning

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3496]
#### Current Behavior
Meshery Adapters persist pattern components in their respective adapter repo (under /templates/oam), and subsequently, bundle these components into the adapter image, but do not version these components.

#### Desired Behavior
Support different versions of same pattern resource. Pattern components (capabilities) should be versioned in accordance with their respective service mesh version from which they were sourced.

#### Implementation
- [ ] Meshery server's registry - Currently, it supports assumes that pattern resources have unique names. Introduce versioning of each component / pattern. 
- [ ] Each adapter implement versioning in the component's json schema, so that this version information can be programmatically referenced downstream.
   - Using Meshery Adapter for Istio as an example, the Istio adapter right now already knows the API version however once we start versioning, Meshery Server will have to start passing this data to istio adapter too, so that it can generate the right "manifests". 

#### Acceptance Tests
- [ ]  Meshery actively manages different versions of the same service mesh using patterns.
- [ ] Adapters have pre-bundled pattern components in adapters, supporting brownfield management of a service mesh of the same version. Adapters do not support air-gapped deployments unto their own.

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
