### ISSUE TITLE
[UI] The Action items for Patterns page

### ISSUE THREAD

**Issue by Abhishek-kumar09** [meshery/meshery#4110]
The new patterns page is just a new born baby that definitely needs some love. 
Here are the action items that works towards making the progress over the pattern page.
We can create a new Issue for each action item and work on it accordingly.
- [x] Extract out the patterns component into it's own file:
https://github.com/meshery/meshery/blob/d11e84b348b48fdfe80823549692640553ab0d85/ui/components/MesheryPatterns.js#L645-L650
- [ ] Add support for multiple applications under same service umbrella
- [ ] Add support to provide and change namespace, and pattern name through forms on the patterns configuration page
- [ ] Add reverse change operation for the the yaml editing.
- [ ] minor: Refractor code for `MesheryMeshInterface/PatternServiceForm.js` since we have already extracted out the copy of it for the use in patterns page
- [x] Apply the changes to the other siblings of patterns, like Applications and Filters.
- [x] Add custom styling to rjsf form

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Zain-Muiz** [comment]
Heyy @Abhishek-kumar09 , Can I work on the 1st issue on the list ? I need to create a new issue for just that specific issue as well right ?

**Comment by warunicorn19** [comment]
@Zain-Muiz you can start working on it, @Abhishek-kumar09 if you could edit your issue and right the names next to each task, it'll be easier to track that way.

**Comment by Abhishek-kumar09** [comment]
> Heyy @Abhishek-kumar09 , Can I work on the 1st issue on the list ? I need to create a new issue for just that specific issue as well right ?

Yeah, you can create a new issue to track the progress :smile_cat:

**Comment by warunicorn19** [comment]
@Zain-Muiz also mention this issue if you create another one.

**Comment by bariqhibat** [comment]
Red texts and capitalize each word have been done on the PR on top

**Comment by Chadha93** [comment]
Let's cover this in refactoring, // @Abhishek-kumar09 @warunicorn19

**Comment by leecalcote** [comment]
@Manish-Rawat-1186 depending upon how far along you are in your Reactjs abilities, this issue might be of interest.

**Comment by leecalcote** [comment]
Completed
