### ISSUE TITLE
[v0.6.0 Release Docs] Release announcement Blog Post! 🎉 🎉  

### ISSUE THREAD

**Issue by Meghana-12** [meshery/meshery#4127]
Hi everyone!
As part of Release Blog for v0.6.0, we have created this epic to organise and ensure the smooth release of the blog. We plan on having a separate blog post for some of the feature highlights. So, if anyone is interested in working on a feature post/section, please feel free to leave a comment here or under the respective issue!  

## Features Highlights
- [ ] Applications (#4128) @Meghana-12 
- [ ] Filters (#4129) @felixfaisal
- [ ] Patterns (#4130) @Abhishek-kumar09 
- [ ] Dynamic Management UIs (#4161) @leecalcote 
- [ ] Connection Wizard (#4162) @iambami
- [ ] **(review needed)** | Increased Platform Support (#4181) @navendu-pottekkat 
- [ ] **(review needed)** | SMI Conformance (#4180) @SirZeck
- [ ] **(review needed)** | Pipelining Service Mesh Specifications (#4179) @navendu-pottekkat @DelusionalOptimist 
- [ ] GitHub Action for SMI Conformance (#4203) @navendu-pottekkat
- [ ] GitHub Action for SMP (#4148) 
- [ ] MeshMap Beta Program (#4178) @leecalcote 

---

#### Guides and Resources
- [v0.6.0 Docs ](https://docs.google.com/document/d/1d8deyqzgsRIGyZGH0gxo-lhspHAWCvdBtY2h1gwLakI/edit?usp=sharing)
- [v0.6.0 Milestone](https://github.com/meshery/meshery/milestone/3)
- [v0.6.0 RoadMap](https://github.com/meshery/meshery/blob/master/ROADMAP.md)
- [v0.5.0 blog](https://layer5.io/blog/announcements/announcing-meshery-v050)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)

**Comment by navendu-pottekkat** [comment]
Increased platform support blog could come under a broader topic like "What's new in mesheryctl". I assume the increased platform support refers to ARM/M1 support (?)

// @leecalcote

**Comment by adithyaakrishna** [comment]
@Meghana-12 @Zain-Muiz Any updates on this? 👀

**Comment by Nikhil-Ladha** [comment]
Looks like all the tasks are completed.
Closing the issue.
