### ISSUE TITLE
[CI] Add integration tests for "/configuration/*" for patterns, filters and applications

### ISSUE THREAD

**Issue by navendu-pottekkat** [meshery/meshery#4582]
#### Current Behavior

There aren't any integration tests that cover Meshery's configuration management functionality.

#### Desired Behavior

An integration test should be written to cover these functionalities.

#### Implementation Notes

* Patterns feature is completely functional now. You should be able to perform CRUD operations with a [valid pattern file](https://github.com/service-mesh-patterns/service-mesh-patterns/tree/master/samples) and configure, apply these.
* Filters are partially functional. Basic CRUD operations are supported. [Sample filters](https://github.com/layer5io/wasm-filters).
* Applications work similar to patterns.

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by s1ntaxe770r** [comment]
🤔  @navendu-pottekkat  are there any similar integration tests I could work off?

**Comment by navendu-pottekkat** [comment]
@s1ntaxe770r We are in need of such tests. You can help with the tests that leverage the Meshery GH actions.

One action that is in need of some help is [mesheryctl-service-mesh-patterns-action](https://github.com/layer5io/mesheryctl-service-mesh-patterns-action)

You can help tie this off and probably use it to deploy and onboard apps in the scheduled performance benchmark workflow: [scheduled-benchmarks.yml](https://github.com/layer5io/meshery-smp-action/blob/master/.github/workflows/scheduled-benchmarks.yml)

**Comment by MarioArriaga92** [comment]
Hey @navendu-pottekkat, looks good no questions for now. you may assign it to me please 🙏🔥

**Comment by MarioArriaga92** [comment]
@leecalcote @navendu-pottekkat @Abhishek-kumar09 

Suggested changes to this issue:
- Title update: Add "/configuration/*" tests
- Description change: 2 sections for Integration &, E2E Tests (like in #1037) as following:
"**Integration Tests (one for each page for CRUD stubbing all server responses):**
- [ ] Add integration tests for /configuration/applications route
- [ ] Add integration tests for /configuration/filters route
- [ ] Add integration tests for /configuration/patterns route
**E2E Tests (these are more usecase or scenario wise as they'll touch multiple routes and multiple pages in each child issue with actual server responses):**
- [ ] Add E2E tests to Deploy Applications/Filters/Patterns Configuration through Meshery UI (#4826)
- [ ] Add E2E tests to Edit Applications/Filters/Patterns Configuration through Meshery UI
- [ ] Add E2E tests to Delete Applications/Filters/Patterns Configuration through Meshery UI"

Intention of grouping Integration tests is that creation if stubbed responses requires page + operation focus (for now these tests have lower priority for us to implement than E2E ones because we want to deferr them until we are confident that client/server communication interfaces are stable (out of BETA, at least)

Also, grouping E2E tests by usecase / end user scenario + multiple pages is to focus on test code reusage to try to reduce maintenance efforts & enforce standard expectations & behavior across the three pages.

**Comment by MarioArriaga92** [comment]
@leecalcote @Abhishek-kumar09 @navendu-pottekkat do we agree on suggestions I made in prior comment? I don't have permissions to apply those changes lol

**Comment by MarioArriaga92** [comment]
PR linked to child issue [4826](https://github.com/meshery/meshery/issues/4826) would cross the 3 checkboxes mentioned in "E2E Tests" section of prior comment I made but still need to check if issues are fixed already (the ones spoken during prior community meeting)

**Comment by Abhishek-kumar09** [comment]
I added some more checkpoints on the parent issue, mentioned by you.

**Comment by leecalcote** [comment]
It'd be great to get these mapped to items in the [Meshery Test Plan](https://docs.google.com/spreadsheets/d/13Ir4gfaKoAX9r8qYjAFFl_U9ntke4X5ndREY1T7bnVs/edit#gid=0).
