### ISSUE TITLE
[UI] Create a Storybook for Meshery UI

### ISSUE THREAD

**Issue by acald-creator** [meshery/meshery#7173]
**UPDATE**
DONE: At this time, I will be moving the Storybook directories outside of `meshery/ui`, as there are issues with trying to create a new component versus the deprecated packages that we currently use in `meshery/ui`.

#### Current Behavior
It would be nice to have a design system for Meshery that can be reused across multiple repos, as we are also supporting others. Even though we have a design system in Figma, we don't have one implemented as a library. Next.js and Storybook have support for `v12` and `v13` and can be great choices in creating a design system library in the long run. To start, we can initialize `ui` with Storybook and start building and testing components.

#### Tasks to complete
- [x] A designated folder in `/ui` to house Storybook components.
    - [ ] Storybook creates `.storybook` and `stories` directories with example components such as `Button`, `Login` and `Header` stories. Storybook also updates `.eslintrc.js` with `plugin:storybook/recommended` rule. 
- [x] Create a new GitHub Label `framework/storybook`
- [ ] Create a new GitHub issue called `issue/epic` or `kind/epic` that outlines sub-tasks / sub-issues and a roadmap
- [ ] Add roadmap as a line in Meshery Architecture desk slide
- [ ] An augmentation of the `contributing-ui` docs with an explanation of the initiative, and optionally a README in `/ui` folder pointing to this docs' section.
- [ ] ~Ensure that Storybook can wire up and support `Material-UI v4` or `MUI v5` theme provider.~
    - [x] Create default light and dark mode toggler for Storybook
- [ ] Wire Storybook to connect to `redux` (`react-redux` or `@reduxjs/toolkit`)
- [ ] Wire Storybook to connect to Relay framework (possible)
- [ ] Add unit testing to Storybook
- [ ] Fix any of the issues that may rise in using Storybook to import current pages in ~`/ui`~ `/storybook`

#### Implementation
MUI v5 Components
- [x] Button
- [x] AppBar
- [x] Chip
- [x] Avatar - (@UsmanDev09)
- [ ] Paper
- [ ] Drawer
- [ ] Tab(s) - open PR https://github.com/meshery/meshery/pull/7860

Meshery UI Components
- [ ] Confirmation Modal
- [ ] Custom Avatar
- [ ] Custom Table Footer
- [ ] Custom Table Select
- [ ] Meshery Notification
- [ ] Meshery Progress Bar
- [ ] Meshery Result Dialog
- [ ] Upload Import (in progress)
- [ ] URL Uploader (in progress)
- [ ] Custom Dialog (in progress)
- [ ] Prompt Modal (in progress)
- [ ] Tooltip Button (done)
- [ ] Catalog Filter (done)
- [ ] Flip Card (partially done)

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Mayaleeeee** [comment]
Hi @acald-creator and @leecalcote, Is this issue done?

**Comment by UsmanDev09** [comment]
Hi @acald-creator, can i work on this issue?

**Comment by UsmanDev09** [comment]
I will start with the Avatar. Once done, I will update you and work on the next components.

**Comment by senali-d** [comment]
@acald-creator I would like to work on the Drawer component.

**Comment by acald-creator** [comment]
@senali-d Sure, I have some of the Drawer components that matches almost what we have in `meshery/ui` but it would be great to have more examples.

**Comment by UsmanDev09** [comment]
Can you please assign me Paper, Drawer and Tabs component too? I am available to work on those. @acald-creator
