### ISSUE TITLE
[UI] Convert React Class components to Function components tracker

### ISSUE THREAD

**Issue by acald-creator** [meshery/meshery#7187]
#### Current Behavior

We have a mixture of Class components and Function components.

To assist with the UI upgrade in terms of `@reduxjs/toolkit` and MUI, it would be nice that we're able to use React Hooks, and create custom hooks to be used throughout the app.

#### Desired Behavior

I will write out the plans of the smallest Class components that can be converted before moving on to the largest one.

We can also discuss any of the ones that should not be migrated and don't have a need to migrate, but it would be nice to migrate in the long run.

#### Implementation

- [x] `ui/pages/404.js` (DONE)
- [ ] `ui/pages/index.js` (WIP)
- [x] `ui/pages/performance/index.js` (DONE)
- [x] `ui/pages/performance/profiles.js` (DONE)
- [x] `ui/pages/performance/results.js` (DONE)
- [ ] `ui/pages/management/index.js`
- [x] `ui/configuration/applications.js` (DONE)
- [ ] `ui/configuration/filters.js` (WIP)
- [x] `ui/configuration/patterns.js` (DONE)
- [ ] `ui/user/preferences.js` (WIP)

---
- [ ] `ui/pages/settings.js` is dependent on `ui/components/MesherySettings.js` (WIP)
- [ ] `ui/pages/smi_results.js` is dependent on `ui/components/MesherySMIResults.js`

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Udit-takkar** [comment]
@acald-creator Much needed refactor. happy to help migrating class components to function components.

**Comment by acald-creator** [comment]
Awesome @Udit-takkar 

I will update this open issues with some of the smallest Class components that can be converted without breaking the app.

I will also open another issue to guide transition to using `@reduxjs/toolkit` as well.

**Comment by 123Vasu** [comment]
I would like to work on this issue.

**Comment by UsmanDev09** [comment]
@acald-creator I can work on the performance and management pages. Please assign it to me

**Comment by ranjanmangla1** [comment]
if nobody is working on it, can i work on it or a part of it?

**Comment by EraKin575** [comment]
@acald-creator  hey!If this issue is still important to be taken care of, please assign me

**Comment by anniepauline** [comment]
Willing to work on it!
