### ISSUE TITLE
[UI] Migrate to `@reduxjs/toolkit` tracker

### ISSUE THREAD

**Issue by acald-creator** [meshery/meshery#7207]
**UPDATE** There is an open PR and open issue to track migrating Meshery UI to the latest libraries and using the latest styles and components from the Sistent Design System.

Open Issue: https://github.com/layer5io/sistent/issues/496
Open PR: https://github.com/layer5io/sistent/pull/498

In the open PR, I've already started work on using the `@reduxjs/toolkit` store. But they are not tested very well because of needing to make sure that the Provider's login works correctly before authenticating and redirecting back to the homepage.

**UPDATE** This milestone has been pushed back to `v7` only because we have couple of tickets that are asking for React Class to Function components conversion, and this is impacted because using the existing implementations of `mapStateToProps` and `mapDispatchToProps` are commonly associated with `connect` HOC component with `react-redux`.

#### Current Behavior
 
Redux has always been a complex library, but they've recently released a package called `@reduxjs/toolkit` which simplifies how you use `react-redux` in the app.

`next-redux-wrapper` has also released a newer version at `v8`, which is vastly different from `v3` and also has support for `@reduxjs/toolit`.

After some research, I found that is best to not just use Redux as the only global state management package for Meshery.

I would like to point out other packages that can be of use with Redux, or without Redux.

* `jotai`
* `xstate`
* `zustand`
* `mobx`

#### Desired Behavior

This is an open issue to track progress after certain milestones occur.

1. https://github.com/meshery/meshery/issues/7187
2. https://github.com/meshery/meshery/issues/7212
3. https://github.com/meshery/meshery/issues/6965

#### Implementation

* Research `@reduxjs/toolkit`
* Consider moving some of the actions to not be used by Redux, and use it as a local state, (perhaps by Next.js or React context)
* ~Create Theme Provider context to toggle light and dark theme~ done in forked branch

Research the current `store.js` and break it down into multiple slices.
* ~update page path and title (could be used as a custom hook)~ Revised to be a Context API
* update user information (could revise data-fetch.js to be a hook and reused within multiple components)
* provider information
* Kubernetes cluster information
* Grafana / Prometheus information
* Modify existing Drawer / App Bar collapse conditions to be used with `useState` instead of redux (WIP)

In this forked branch at https://github.com/nebula-aac/meshery/tree/feat/reduxjs-toolkit-migration, here are the list of features within the Redux store that will be implemented. Please note that these are in progress and already created in the forked branch.
- [ ] Filters page state
- [ ] Confirmation modal state
- [ ] Grid state for Filters page
- [ ] Kubernetes config state
- [ ] Transform property state (could be revised)
- [ ] User update state

#### Mockups

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by roopeshsn** [comment]
Hi @acald-creator! I would like to work on this.

**Comment by acald-creator** [comment]
@roopeshsn Awesome

Thanks for reaching out. This migration tracker is aiming for `v0.8` milestone while we are still in `v0.6`.

It is quite possible to achieve this sooner but I will be updating this issue as time goes by to list some of the changes that will needs to be made.

In the meantime, you can still help and provide insights if you have any.

**Comment by roopeshsn** [comment]
Sure, @acald-creator! Let me see the existing implementation of react-redux and provide insights if any.

**Comment by nebula-aac** [comment]
bump

**Comment by Pranjal7852** [comment]
@nebula-aac I would like to work on this issue

**Comment by Yashsharma1911** [comment]
// @senali-d @sudhanshutech
