### ISSUE TITLE
[CI] Bare Metal Deployment of Meshery Playground

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7385]
# Prologue
See related issue: **Multi-user cloud native playground #7020**

### Current Behavior
The community is in process of deploying a 2-node Kubernetes cluster on two bare metal servers hosted in the CNCF Labs. See Equinix's guide for deploying [Kubernetes on bare metal](https://deploy.equinix.com/developers/guides/kubernetes-intro).

Node Hardware Configuration:
<img width="945" alt="Screenshot 2023-03-23 at 10 05 41 AM" src="https://user-images.githubusercontent.com/7570704/227369069-8622c61a-c076-4f1e-bb27-4fa8cf511cca.png">

### Desired Behavior
- An open playground for all to explore and learn CNCF projects.
- We are currently using Kubeadm as our preferred tool for this deployment. We believe that having a collaborative effort will ensure a successful implementation and lead to a more streamlined process.

See the [Meshery Architecture deck](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#) for diagrams on Meshery and its deployment models.

## Implementation Phase 1
_Vision: A shared, Wild West playground in which learning and collaboration is facilitated._
     
### Resetting Environment
- [ ] ❓**Scheduling Playground Reset:** Use the [meshery-smp-action](https://github.com/layer5io/meshery-smp-action) GitHub Action as a template for creating a GitHub workflow to provision and deprovision the the Kubernetes cluster. Create a new workflow with schedule on 24 hour reset playground daily.
- [ ] ❓**Playground Reset Mechanism**
    - [ ] ❓Identify and implement a mechanism for daily playground reset. Different "resets" possible (decommission bare metal, reinstall OS, reinstall Kubernetes, or wipe Namespace(s)).

### Provisioning / Deprovisioning Enviorment
- [ ] If bare metal reset is used, then use Equinix `metal`  CLI for provisioning machines. 
- [ ] Research available Equinix playbook to provisioning Kubernetes.
- [ ] Create bash script and/or use Tinkerbell and/or Ansible to initialize Kubernetes cluster and deploy Meshery using [Meshery Helm Chart](https://docs.meshery.io/installation/platforms/kubernetes)  or `mesheryctl`

### Environment Configuration
- [ ] @alaeddinebenhassir Deploy Nginx Ingress controller  
    - [x] @revolyssup share NGINX ingress config that supports websockets
    - [x @alaeddinebenhassir Extra config to be passed from annotations to Ingress resource (for websocket consideration)
    - [x] @alaeddinebenhassir  Change Meshery service to NodePort and use the Loadbalancer IP for ingress
    - [x] @alaeddinebenhassir Point Ingress service as type LoadBalancer
    - [ ] @alaeddinebenhassir User cert manager with ingress controller (straight-forward) to generate certs.
- [x] @Revolyssup provision static IP address.
- [x] @leecalcote Create DNS A record for demo.meshery.io
- [ ] ❓ Selection and configuration of a CNI provider.
- [ ] ❓ Diagram the Meshery Playground deployment in a MeshMap design.
- [ ] ❓ Create Helm Chart for Meshery Cloud.

### Documentation
- [ ] #2202 
    New Page: "Deploying Meshery into Production"
- [ ] ❓  #7422
- [ ] ❓ #7427

## Acceptance Tests
1. Meshery Playground Kubernetes Service is load-balanced and publicly exposed behind a public IP and DNS A record for everyone to access.
1. Both nodes are tainted to allow scheduling of workloads (control plane node is capable of receiving workloads).
1. Meshery Playground Kubernetes Deployment has redundancy across both nodes in the cluster.

## Implementation Phase 2
_Vision: Multi-tenancy, and isolation. tIndividually, playground in which learning and collaboration is facilitated._

### Operations
- [ ] ❓ Identity monitoring considerations; How to monitor the health of a Meshery Deployment
   - [ ] ❓ Liveness, Readiness probes
   - [ ] ❓ Metrics, Logs, Traces

### Configuration
- [ ] ❓ Long-lived management cluster running Meshery

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by rghdrizzle** [comment]
Hey I would like to work on this along with other contributors who wants to work on it . 
This is what I understood from the instructions:
1. Configure the pipe to provision k8s nodes on the bare metal sever 
2. The playground has to end every 24 hours ( so would that mean that the nodes has to deprovision every 24hrs?)
3. The playground service has to be or type load balancer 
4. The deployment has to present in both the nodes as a replica 
5. Should use taints and toleration for the scheduling of the nodes.

**Comment by harsh-del** [comment]
Hey I would like to contribute on this

**Comment by Meghakiddie** [comment]
Hey! I would like to contribute on this

**Comment by rav121** [comment]
I am in 100% în. I can take care of deployments manifests and helm of meshery

**Comment by leecalcote** [comment]
Here's a recording of the [Meshery Playground Deployment Planning](https://www.youtube.com/watch?v=q_YJoSI4_OI) meeting from Friday, March 24th.

**Comment by leecalcote** [comment]
> I am in 100% în. I can take care of deployments manifests and helm of meshery

Awesome, @rav121. If you would you like to choose one of the of unassigned tasks above, we'll get it assigned.

**Comment by leecalcote** [comment]
> Hey I would like to work on this along with other contributors who wants to work on it . This is what I understood from the instructions:
> 
> 1. Configure the pipeline to provision k8s nodes on the bare metal sever
> 2. The playground has to end every 24 hours ( so would that mean that the nodes has to deprovision every 24hrs?)
> 3. The playground service has to be of type load balancer
> 4. The deployment has to be present in both the nodes as a replica
> 5. Should use taints and toleration for the scheduling of the nodes.

Yes, you're quite close to the mark. The issue description has many more details now.

**Comment by rghdrizzle** [comment]
> > Hey I would like to work on this along with other contributors who wants to work on it . This is what I understood from the instructions:
> > 
> > 1. Configure the pipeline to provision k8s nodes on the bare metal sever
> > 2. The playground has to end every 24 hours ( so would that mean that the nodes has to deprovision every 24hrs?)
> > 3. The playground service has to be of type load balancer
> > 4. The deployment has to be present in both the nodes as a replica
> > 5. Should use taints and toleration for the scheduling of the nodes.
> 
> @rghdrizzle, yes, you're quite close to the mark. The issue description has many more details now.

Alright got it , Can I work on the helm chart for the meshery cloud??

**Comment by alaeddinebenhassir** [comment]
@leecalcote Regarding the Reset mechanism , i thing we can go with Reseting the cluster instead of completely reinstalling Kubernets , starting with `kubeadm reset && iptables -F`
take a look at the fellowing scripte on my fork 
https://github.com/alaeddinebenhassir/meshery/tree/Playground-Metal-Deployement/install/playground/Metal
