### ISSUE TITLE
Left over items for connections, environments and workspace in Meshery and remote provider

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#9652]
### Current Behavior

Following are the items which need to be completed.

- [x] Add filtering in connections API and fix UI to filter connections in remote provider (/api/integrations/connections) @Yashsharma1911 
- [x] Test PR #9548 for connection registration with Prometheus and merge
- [x] Merge environment page PR in Meshery #9647 @senali-d 
- [x] Show icons in filters sidebar in remote provider connections page
- [x] Fix duplication of states in state selector in connections page. @aabidsofi19 
- [x] Workspace page in Meshery  #9722 @senali-d
- [x] Change kepple green color to primary color in environment and registration modal in meshery
- [X] Dark mode changes in environment page #9705 @senali-d 
- [x] Connections Page: Assignment of Environments to Connection https://github.com/meshery/meshery/pull/9637

### Mockups

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by theBeginner86** [comment]
updated description with assignment of connections to environments PR 👍

**Comment by Yashsharma1911** [comment]
> updated description with "Assignment of Connections to Environment" PR 👍 

Thankyou @theBeginner86

**Comment by sudhanshutech** [comment]
#9840 -> Issue related to this area

**Comment by Yashsharma1911** [comment]
Thankyou everyone this issue is completed
