### ISSUE TITLE
Implementation of permission framework in Meshery UI

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#9721]
### Current Behavior

Meshery UI lacks a permissions framework. The existing internal implementation is extremely simple and fragile and is “does the user have a role with this name assigned?“. So, it must be completely set aside / rewritten.

### Desired Behavior

We're aiming to implement CASL which is dynamic and extensible permissions framework, 

- Render UI based on user's permission within a selected organization.
- Improved user experience with the ability to re-render the UI after switching the organization.
- Shift from role-based implementation to keys-based implementation for granular control.

### Implementation

- [X] [UI] Integrate CASL in meshery UI. #8945 @Mohith234 
- [x] [Server] Add keys API in meshery UI as capabilities. #9731 
- [x] [Server] Seed new keys for Meshery in remote and local provider [#1832](https://github.com/layer5io/meshery-cloud/pull/1832/files) #9771 
- [x] [UI] Use Redux, Rtk to update CASL ability with fetched keys to make it available to the application. #9778 
- [x] [UI] Add permission constant file in UI and Enforce CASL in UI #9778 
- [ ] [UI] Expose CASL in MeshMap extension point

### Acceptance Tests

- [x] Rerender UI on switching organization.

### Mockups

No mockups provided. Visual representation may be added as needed.

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by sudhanshutech** [comment]
@Yashsharma1911 i think you can close this issue and create a separate for `MeshMap extension point` will `issue/willfix` because meshery supports casl now

**Comment by sudhanshutech** [comment]
> @Yashsharma1911 i think you can close this issue and create a separate for `MeshMap extension point` will `issue/willfix` because meshery supports casl now

@Yashsharma1911

**Comment by Yashsharma1911** [comment]
> > @Yashsharma1911 i think you can close this issue and create a separate for `MeshMap extension point` will `issue/willfix` because meshery supports casl now
> 
> @Yashsharma1911 

@sudhanshutech we can however let's keep this one to maintain history of issue here

**Comment by Yashsharma1911** [comment]
This issue is fixed
