### ISSUE TITLE
[UI] Enhance Registry page in Settings

### ISSUE THREAD

**Issue by Yashsharma1911** [meshery/meshery#9775]
### Current Behavior
The underlying code for this UI component is… less than stellar, but really, really needs to be a commonly referenced index for Meshery admins / users.

Meshery admins need to be able to confirm which models and components are registered, what host serves those components, what their version is, disable/enable models and so forth.

Slack conversations - [messages](https://layer5io.slack.com/archives/C023QGMSH8D/p1704016045558569)

### Expected Behavior
Understand which designs use with components. What models are the most popular by use…. and on and on.

### Screenshots/Logs
https://layer5io.slack.com/files/U05RS2F9GAC/F06BXHHS4CD/screencast_from_2023-12-31_15-13-54.webm

### Finding & task need to be done

# Models/Components tab:

This tab should give users an overview of what models are and how many MeshModels are out there, along with the actions they can perform.

**Questions:**
1. Does Meshery allow the export of individual models/components? (Learn more about MeshModels and component [here](https://docs.google.com/presentation/d/1SQMfyu5shjpGKlYONdVzOtd7UYTgLWBcgUvHMLCZ2tY/edit#slide=id.g28d3a0f18b4_0_292))
2. Does Meshery allow importing new models/components, or creating a model? If so, where can users create a new model?
3. Does Meshery track import history, including the user who imported a component?
4. Can we disable any MeshModel? If yes, is it disabled for all workspaces or a particular workspace?
5. Can I edit component/model details after import? If yes, where can I do that?
6. Where can we see the status of components/models, including whether they are enabled or disabled?
7. How can I enable disabled components?
8. **Failed Registration:**
   - Where can I view failed-to-register models or components? And their logs.
   - Can I re-register them, and if so, how?
9. Allow users to pin a component/model in tree view.
10. Trying to show data more in Metrics format (easy to debug and understand).
11. Determine how many designs in a particular organization are using a specific component/model.

## Improvement suggestions in current UI:
- [ ] Support filtering options: Implementing basic search by name, along with filters based on status, category, sub-category, or based on MeshModel.
- [x] Update routing based on expanding or clicking on modal or component, to support deep linking #9939 
- **Tree Structure:**
  - [X] Add horizontal lines to the tree for visual clarity. #9989 
  - [X] Enhance duplicate switcher. #9939 
  - [x] Ensure the tree contains unique modal names, even with different versions. Consider displaying all available versions when opening a modal.
  - [X] Fix the issue of displaying incorrect subcategories. #10208
  - [X] Show all modals when user opens registrant tree instead of cutting of few #10007 
  - [X] Fix expand and collapse icons #10208
  - [ ] Allow users to ignore models #10171 
  - [ ] Support import and export of models as OCI format
  - [ ] https://github.com/meshery/meshery/issues/11352

### Component Tab:

- [X] Address the issue of not showing all components when returning to the tab after switching to others.
- [ ] Add a loading indicator at the bottom during scroll loading.
- [X] If a component is not found on search, show an empty state instead of showing an empty tree.
- [X] Fix the issue of not showing relationships in the tree in modals tab.

### Modal Tab:

- [X] When clicking on a component in the modal tab, it adds to the bottom of the already opened data on the right side details section. Adjust this behavior by displaying data of what is selected. #10208
- **Missing SubType Value:**
  - [X] The sub-type value is missing from the modal details section on the right side. (UI supports however we don't seed sub-category info of the model in DB)
- **Subcategory Duplicate:**
  - [X] The subcategory is identical to the component's display name. Is this intentional? #10208
- Fetch

# Tree View Enhancements:

**Visual Differentiation:**
- Can we add icons to the left of names in the tree to differentiate between models, components, and relationships? (Hold thought here)

# Relationship tab:

- The UI should serve as a single source of truth for visualizing and understanding all relationships between components within and across models.

**Questions:**
1. How can a user create their own custom relationship?
2. How can a user customize an existing or custom relationship while showing the impact of its change?
3. Where can a user read more about relationships and how they are used in Meshery?

**Improvement suggestion in current UI:**
- **Unclear relationship impact:**
  - [ ] It's difficult to understand how modifying or deleting a relationship might affect dependent models or components. (If we allow doing so)
- **Limited information:**
  - [ ] The current UI only displays the number of relationships, lacking specifics like how many components use a particular relationship or relationship statuses (enabled or disabled).
- **Issue:**
  - [X] Investigate the cause of empty boxes appearing in the tree within the relationship tab.
  - [ ] Duplicates can be referred to "overlapping relationships" (low priority) 

# Registrant tab:

- See all modals registered by a particular registrant.
- **Issue:**
  - [X] Investigate why the registrant page is not loading all 6 registrants.
  - [x] Registrant are connection, change UI of registrant as chip to represent them as connection 

# Common issues in tab
- [X] Migrate registry to RTK
- [X] Fix routing of settings page
- [X] Showing more info about selected items on details page, like icon, description, and more

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Yashsharma1911** [comment]
// @sudhanshutech

**Comment by sudhanshutech** [comment]
Let me know @Yashsharma1911 with any task here

**Comment by vaibhavpnimkar** [comment]
#9595 needs to be re-open 
![Screenshot (220)](https://github.com/meshery/meshery/assets/128807866/848d3912-ae60-4a6e-b1ff-a11a3273f71c)

**Comment by vaibhavpnimkar** [comment]
Toggle button in settings/registry 

https://github.com/meshery/meshery/assets/128807866/da48454e-68c0-45e2-9fd4-4a42fa7a81bd

Expand toggle button not working properly

**Comment by Yashsharma1911** [comment]
Thankyou @vaibhavpnimkar let's meet tomorrow to discuss more if you are free

**Comment by vaibhavpnimkar** [comment]
sure @Yashsharma1911  let me know in which time duration you are free?

**Comment by Yashsharma1911** [comment]
Are you available today at 10 PM maybe, ping me on slack after that

**Comment by vaibhavpnimkar** [comment]
okay !!!

**Comment by leecalcote** [comment]
@AjaxAueleke there are a _number_ of issues with this UI. There might be a few items you could pick off and fix here.

**Comment by Yashsharma1911** [comment]
@vaibhavpnimkar I have updated the issue

**Comment by vaibhavpnimkar** [comment]
hey @Yashsharma1911 i am struglling with local dev env of meshery i would like to unassign this issues for right now whenever it will work i will start working

**Comment by Yashsharma1911** [comment]
> hey @Yashsharma1911 i am struglling with local dev env of meshery i would like to unassign this issues for right now whenever it will work i will start working

Ohh no worries @vaibhavpnimkar, have you posted that issues on discuss.meshery.io? till someone answer there or you figure out, can you help few PRs gettings reviewed and merged in meshery.io website?

**Comment by Yashsharma1911** [comment]
Closing this issue as new issue is created to track registry enhancements
